version: '3.1'

services:

  guestbook:
    restart: always
    ports:
      - 3005:3005
    build:
      context: ./guestbook
      dockerfile: Dockerfile
    depends_on:
      - "mongo"

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - "guestbook"

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
    - ./config.ini:/etc/grafana/config.ini
    - ./dashboards:/var/lib/grafana/dashboards
    - ./provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - "prometheus"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - "mongo"

  init-db:
#    image: captainmatt/db-init-go:0.0.1
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DATABASE: test
      DB_COLLECTION: guests
    volumes:
      - ./db-init/insert.sql:/go/src/db-init/insert.sql
    build:
      context: ./db-init
      dockerfile: Dockerfile
    depends_on:
      - "mongo"

